### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by zzl2022** [Gollini/NSCLC_Radiogenomics#1]
This is an excellent repository. But I failed to reproduce the script. Can you provide a more detailed requirements.txt accompanying dependency versions?

**Comment by Gollini** [comment]
Thanks for your comment, @zzl2022. Can you please be more specific? Which part are you not able to reproduce?

**Comment by zzl2022** [comment]
Dear Dr. Gollini,

 

Greetings for the day!

 

Thank you for your letter.




You can download the attachment to view my confusion about your repository.
 

It would be very grateful if you could help me.  I look forward to hear from you soon!
 

Best Regards,

 

Zhilei Zhao

Beijing Institute of Technology

Beijing China










At 2023-03-30 02:27:59, "Gollini" ***@***.***> wrote:

Thanks for your comment, @zzl2022. Can you please be more specific? Which part are you not able to reproduce?

**Comment by Gollini** [comment]
Dear @zzl2022,
Maybe there was a mistake on my side, but I can't find the attachment.
If you can please send it again, I will be more than glad to help you.

**Comment by Gollini** [comment]
Dear @zzl2022, 
I have updated the requirements.txt with the dependencies versions when building this repository.
Please let me know if the problem continues. The repository was built five months ago, so maybe an update from my side is required.

**Comment by zzl2022** [comment]
> Dear @zzl2022, Maybe there was a mistake on my side, but I can't find the attachment. If you can please send it again, I will be more than glad to help you.

Dear Dr. Gollini,

Thank you for your patient reply!

I have uploaded the attachment again.

[Issues about the public Github repository.docx](https://github.com/Gollini/NSCLC_Radiogenomics/files/11145531/Issues.about.the.public.Github.repository.docx)

Thank you for your willingness to help me.
